# Generated by Django 6.0.2 on 2026-02-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_uid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('patient_id', models.CharField(blank=True, max_length=255)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_uid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('source_format', models.CharField(choices=[('DICOM', 'DICOM'), ('NIFTI', 'NIfTI')], default='DICOM', max_length=10)),
                ('num_slices', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='diacom_app.study')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['study', 'series_uid'],
            },
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_uid', models.CharField(db_index=True, max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('slice_location', models.FloatField(default=0.0)),
                ('image_position', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='diacom_app.series')),
            ],
            options={
                'ordering': ['series', 'slice_location'],
                'unique_together': {('series', 'instance_uid')},
            },
        ),
    ]
